server:
  port: 8082

spring:
  application:
    name: transaction-service

  datasource:
    url: jdbc:postgresql://localhost:5433/transactiondb
    username: payflow
    password: payflow123
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        format_sql: true

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.type.mapping: transactionEvent:com.payflow.transaction.TransactionEvent