replicaCount: 1

image:
  repository: 819048646487.dkr.ecr.us-east-1.amazonaws.com/payflow/transaction-service
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8082

env:
  SPRING_DATASOURCE_URL: jdbc:postgresql://transaction-db:5433/transactiondb
  SPRING_DATASOURCE_USERNAME: payflow
  SPRING_DATASOURCE_PASSWORD: payflow123
  SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092

resources:
  requests:
    memory: "256Mi"
    cpu: "250m"
  limits:
    memory: "512Mi"
    cpu: "500m"
