package com.payflow.transaction;

import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import java.math.BigDecimal;
import java.time.LocalDateTime;

@Entity
@Table(name = "transactions")
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class Transaction {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * The unique ID for this transaction
     * Generated by us — like a receipt number
     */
    @Column(name = "transaction_id", nullable = false, unique = true)
    private String transactionId;

    /**
     * Which account money is leaving from
     */
    @Column(name = "from_account", nullable = false)
    private String fromAccount;

    /**
     * Which account money is going to
     */
    @Column(name = "to_account", nullable = false)
    private String toAccount;

    /**
     * How much money is moving
     */
    @Column(name = "amount", nullable = false)
    private BigDecimal amount;

    /**
     * Type of transaction — TRANSFER, DEPOSIT, WITHDRAWAL
     */
    @Enumerated(EnumType.STRING)
    @Column(name = "type", nullable = false)
    private TransactionType type;

    /**
     * Current status of the transaction
     */
    @Enumerated(EnumType.STRING)
    @Column(name = "status", nullable = false)
    private TransactionStatus status;

    @Column(name = "description")
    private String description;

    @Column(name = "created_at", updatable = false)
    private LocalDateTime createdAt;

    @PrePersist
    protected void onCreate() {
        createdAt = LocalDateTime.now();
        status = TransactionStatus.PENDING;
    }
}